hopsworks:
  project: taxi_demand_forecasting
  feature_group:
    name: hourly_taxi_rides
    version: 1
    description: NYC taxi rides recorded in unix time (milliseconds), at an hourly frequency
    primary_key:
      - location_id
      - unix_time_ms
    event_time: unix_time_ms
    online_enabled: True
  model_registry:
    model_name: one_step_forecaster
    version: 1
train:
  non_features:
    - location_id
    - pickup_time
    - target
  CatBoostRegressor:
    loss_function: RMSE
    silent: True # catboost's version of 'verbosity'
    thread_count: -1 # catboost's version of 'n_jobs'
  LGBMRegressor:
    objective: regression
    metric: rmse
    early_stopping_rounds: 50
    verbosity: -1
    n_jobs: -1
  XGBRegressor:
    objective: reg:squarederror
    eval_metric: rmse
    early_stopping_rounds: 50
    n_jobs: -1
utils:
  taxi_zone_columns:
    - object_id
    - shape_length
    - shape_area
    - zone
    - location_id
    - borough
    - geometry
