ingest:
  raw_columns:
    - pickup_datetime
    - location_id
  processed_columns:
    - location_id
    - pickup_datetime
    - rides
  taxi_zone_columns:
    - object_id 
    - shape_length 
    - shape_area 
    - zone 
    - location_id 
    - borough 
    - geometry
train:
  CatBoostRegressor:
    loss_function: RMSE
    silent: True # catboost's version of 'verbosity'
    thread_count: -1 # catboost's version of 'n_jobs'
  LGBMRegressor:
    objective: regression
    metric: rmse
    early_stopping_rounds: 50
    verbosity: -1
    n_jobs: -1
  XGBRegressor:
    objective: reg:squarederror 
    eval_metric: rmse 
    early_stopping_rounds: 50 
    n_jobs: -1
hopsworks:
  project: taxi_demand_forecasting
  feature_group:
    name: univariate_time_series
    version: 1
    description: NYC taxi rides recorded at an hourly frequency
    primary_key:
      - location_id
      - unix_epoch_ms
    event_time: unix_epoch_ms
    online_enabled: True
  model_registry:
    model_name: forecasting_model
    version: 1