data:
  columns:
  - location_id
  - pickup_time
  - n_rides
  duration: 14
  target_column: n_rides
  temporal_column: pickup_time
model:
  n_folds: 5
  train_pct: 0.8
  test_size: 4
  xgbregressor:
    objective: reg:squarederror
    eval_metric: rmse
    early_stopping_rounds: 50
    n_jobs: -1
  hyperparams:
    - n_estimators
    - max_depth
    - learning_rate
    - min_child_weight
    - reg_alpha
