name: feature-pipeline

on:
  schedule:
    - cron: '0 * * * *' # pipeline will run every hour; https://crontab.guru/#0_*_*_*_*

  # allows the pipeline to be executed manually from GitHub
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.10
  POETRY_VERSION: 1.8.3
  POETRY_URL: https://install.python-poetry.org

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Cache Poetry cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Run feature pipeline script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: make features