name: training-pipeline

on:
  schedule:
    - cron: '0 0 * * *' # pipeline will run every day at midnight; https://crontab.guru/#0_0_*_*_*

  # allows the pipeline to be executed manually from GitHub
  workflow_dispatch:

jobs:

  training_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10.14
        uses: actions/setup-python@v5 # https://github.com/actions/setup-python/releases
        with:
          python-version: '3.10.14'

      - name: Install poetry
        uses: snok/install-poetry@v1 # https://github.com/snok/install-poetry
        with:
          virtualenvs-in-project: true

      - name: Load cached dependencies
        uses: actions/cache@v4 # https://github.com/actions/cache/releases
        id: cached-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-dependencies.outputs.cache-hit != 'true'
        run: make install

      - name: Execute training pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: make train
