name: training-pipeline

on:
  schedule:
    - cron: '0 0 * * *' # pipeline will run every day at midnight

  # allows the pipeline to be executed manually from GitHub
  workflow_dispatch:

env:
  POETRY_URL: https://install.python-poetry.org
  POETRY_VERSION: 1.8.3

jobs:
  training_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4

      - name: Cache Poetry cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-3.10-${{ env.POETRY_VERSION }} # 3.10 is Python version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Execute training pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: make training
